Project/BurgerApp/Controllers/AdminActionsController.cs
using BurgerApp.Models;
using BurgerApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.Controllers
{
    public class AdminActionsController : Controller
    {
        readonly IRegisterS _registerS;
        public AdminActionsController(IRegisterS registerS)
        {
            _registerS = registerS;
        }
       

        //view all burgers 
        public IActionResult GetAllBurgers()
        {
            List<Burger> burgers = _registerS.GetAllBurgers();
            return View(burgers);

        }

        //add burgers
        [HttpGet]
        public ActionResult AddBurger()
        {
            return View();
        }

        //take that input and add to table
        [HttpPost]

        public ActionResult AddBurger(Burger burger)
        {
            try
            {
                _registerS.AddBurger(burger);
                TempData["AddBurger_Alert"] = "Burger added successfully !!";
                return RedirectToAction("GetAllBurgers");
            }
            catch
            {
                return RedirectToAction("AddBurgerEx", "Exceptions");


            }
        }
        //delet burger
        [HttpGet]
        public ActionResult DeleteBurger(int id)
        {
            Burger burger = _registerS.FindRecordById(id);

            return View(burger);
        }
        [HttpPost]
        public ActionResult DeleteBurger(Burger burger)
        {
            try
            {
                _registerS.DeleteBurger(burger.Id);
                TempData["DeleteBurger_Alert"] = "Burger Deleted successfully !!";

                return RedirectToAction("GetAllBurgers");
            }
            catch
            {

                return RedirectToAction("DeleteBurgerEx", "Exceptions");
             }

        }

        //edit burger
      
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var burger = _registerS.FindRecordById(id);
            return View(burger);
        }

        [HttpPost]
        public ActionResult Edit(Burger burger)
        {
            try
            {
                _registerS.Edit(burger);
                TempData["EditBurger_Alert"] = "Burger updated successfully !!";

                return RedirectToAction("GetAllBurgers");

            }
            catch
            {
             return RedirectToAction("EditEx", "Exceptions");

            }

        }

    }
}

Project/BurgerApp/Views/AdminActions/AddBurger.cshtml
@model BurgerApp.Models.Burger

@{
    ViewData["Title"] = "AddBurger";
}

<head>
    <style>
        body{
           
            background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
        }
          .row{
            justify-content:center;
            background-color:transparent;
            font-size:20px;


        }
        input{
            height:40px;

        }
        #heading{
             text-align:center;
        }

    </style>
</head>
<h1 id="heading">Add Burger</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddBurger">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Burger_Name" class="control-label"></label>
                <input asp-for="Burger_Name" class="form-control" required/>
                <span asp-validation-for="Burger_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Burger_Location" class="control-label"></label>
                <input asp-for="Burger_Location" class="form-control" required />
                <span asp-validation-for="Burger_Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" required/>
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" max="1000" min="10"   class="form-control" required/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input asp-for="Img" type="url" class="form-control" required/>
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add Burger" class="btn btn-success" />
            </div>
            <div>
    <a asp-action="GetAllBurgers">Back</a>
</div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

Project/BurgerApp/Views/AdminActions/DeleteBurger.cshtml
@model BurgerApp.Models.Burger

@{
    ViewData["Title"] = "DeleteBurger";
}
<head>
    <style>
       body{
           
            background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
        }
     .row{
         justify-content:center;
         font-size:20px;

     }
     h1{
         text-align:center;
     }
    </style>
</head>



<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Burger</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Burger_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Burger_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Burger_Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Burger_Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="DeleteBurger">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />  | 
        <a asp-action="GetAllBurgers">Back</a>
    </form>
</div>

Project/BurgerApp/Views/AdminActions/Edit.cshtml
@model BurgerApp.Models.Burger

@{
    ViewData["Title"] = "Edit";
}
<head>
    <style>
       body{
           
            background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
        }
     
     .row{
         justify-content:center;
         font-size:20px;

     }
     h1{
         text-align:center;
     }
    </style>
</head>
<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Burger_Name" class="control-label"></label>
                <input asp-for="Burger_Name" class="form-control" />
                <span asp-validation-for="Burger_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Burger_Location" class="control-label"></label>
                <input asp-for="Burger_Location" class="form-control" />
                <span asp-validation-for="Burger_Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input asp-for="Img" type="url" class="form-control" required/>
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
            <div>
    <a asp-action="GetAllBurgers">Back</a>
</div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Project/BurgerApp/Views/AdminActions/GetAllBurgers.cshtml
@model IEnumerable<BurgerApp.Models.Burger>

        @{
            ViewData["Title"] = "GetAllBurgers";
        }
@if(TempData["AddBurger_Alert"] != null)
{
     <div class="alert alert-success" role="alert">
        @TempData["AddBurger_Alert"]
    </div>
}
@if(TempData["EditBurger_Alert"] != null)
{
     <div class="alert alert-success" role="alert">
        @TempData["EditBurger_Alert"]
    </div>
}
@if(TempData["DeleteBurger_Alert"] != null)
{
     <div class="alert alert-success" role="alert">
        @TempData["DeleteBurger_Alert"]
    </div>
}
                               
<button type="button" class="btn btn-info" asp-controller="AdminActions" asp-action="AddBurger"><a asp-controller="AdminActions" asp-action="AddBurger">Add Burgers -></a>
 </button>
<h1>Burgers List</h1>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var item in Model)
            {
                <div class="col">
                    <div class="card">
                        <div class="card-body">

                            <h5 class="card-title">
                                <a>@Html.DisplayFor(modelItem => item.Burger_Name)</a>
                            </h5>
                            <!-- Text -->
                            <img class="card-img-top" src=@item.Img  alt="Card image cap" height="300px" width="300px">
                            <p class="card-text">
                                <h3 hidden>Id : @Html.DisplayFor(modelItem => item.Id)</h3>
                                <h5>Available at : @Html.DisplayFor(modelItem => item.Burger_Location)</h5>
                                <h4>Price : @Html.DisplayFor(modelItem => item.Price)</h4>
                                <h4>Quantity : @Html.DisplayFor(modelItem => item.Quantity)</h4>
                                <button type="button" class="btn btn-info"><a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                </button>
                                <button type="button" class="btn btn-info"><a asp-action="DeleteBurger" asp-route-id="@item.Id">Delete</a></button>
                            </p>
                        </div>
                    </div>
                </div>
                }
         <div>
    </div>
            