Project/BurgerApp/Models/Buy.cs
namespace BurgerApp.Models
{
    public class Buy
    {
        public int Id { get; set; }
        public int Burger_Id { get; set; }
        public string? User_Name { get; set; }
        public string? Burger_Name { get; set; }
        public string? Burger_Location { get; set; }
        public int Quantity { get; set; }
        public float Price { get; set; }

        public string Img { get; set; }
        public DateTime DateTime { get; set; }
    }
}

Project/BurgerApp/Controllers/UserActionsController.cs
using BurgerApp.Context;
using BurgerApp.Models;
using BurgerApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.Controllers
{
    public class UserActionsController : Controller
    {
        readonly IRegisterS _registerS;
        public UserActionsController(IRegisterS registerS)
        {
            _registerS = registerS;
        }

        //view all burgers 
        public IActionResult AllBurgers()
        {
            
            List<Burger> burgers = _registerS.AllBurgers();
            return View(burgers);

        }

        //add burgers to cart
       
        //[HttpGet]
        //public ActionResult AddToCart()
        //{
        //    return View();
        //}

        //take that input and add to table
        
        public ActionResult AddToCart(int id)
        {
            try
            {
                string name = HttpContext.Session.GetString("User_Name");
                _registerS.AddToCart(id,name);
                TempData["AddToCart_Alert"] = "Burger added successfully !!";

                return RedirectToAction("User_Home","Register");
            }
            catch
            {
                return RedirectToAction("AddToCartEx","Exceptions");

            }
        }

        [HttpGet]
        public ActionResult Buy()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Buy(int id, int Quantity)
        {
            try
            {
                
                string name = HttpContext.Session.GetString("User_Name");
                _registerS.Buy(id, name, Quantity);
                if (true) { 

                    return RedirectToAction("ViewBill");
                }
                else
                {
                    TempData["Buy_Alert"] = "item out of stock!";
                    return RedirectToAction("User_Home");
                }
            }
            catch
            {

                return RedirectToAction("BuyEx", "Exceptions");

            }
        }

        public ActionResult RemoveCartItem(int id)
        {
            try
            {
                var name = HttpContext.Session.GetString("User_Name");
                _registerS.RemoveCartItem(id, name);
                TempData["RemoveCartItem_Alert"] = "Burger removed successfully !!";

                return RedirectToAction("User_Home", "Register");
            }
            catch
            {
               return RedirectToAction("RemoveCartItemEx", "Exceptions");

             }
        }

        public ActionResult RemoveFromBill(int id)
        {
                var name = HttpContext.Session.GetString("User_Name");
                _registerS.RemoveFromBill(id, name);

                return RedirectToAction("ViewBill");
        }





        public ActionResult ViewCart()
        {
            
                var name = HttpContext.Session.GetString("User_Name");
                List<Cart> cart = _registerS.ViewCart(name);
                return View(cart);
               
            }

        //edit cart items
        //[HttpGet]
        //public ActionResult EditCart(int id)
        //{
        //    var cart = _registerS.FindRecordById(id);
        //    return View(cart);
        //}

        //[HttpPost]
        //public ActionResult EditCart(Cart cart)
        //{
        //    _registerS.EditCart(cart);
        //    return RedirectToAction("AllBurgers");

        //}

        //public ActionResult PayBill()
        //{
        //    return View();
        //}
        public ActionResult Logout()
        {
            return RedirectToAction("Login");
        }

        
        public ActionResult ViewBill()
        {

            var name = HttpContext.Session.GetString("User_Name");
            List<Buy> buy = _registerS.ViewBill(name);
            return View(buy);

        }
        public ActionResult Confirm(int id)
        {
            var User_Name = HttpContext.Session.GetString("User_Name");
            _registerS.History(id,User_Name);
            return View();

        }

        public ActionResult OrderHistory()
        {
             var name = HttpContext.Session.GetString("User_Name");
             List<History> history = _registerS.OrderHistory(name);
             return View(history);
    }
    }
}

Project/BurgerApp/Views/UserActions/AddToCart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

Project/BurgerApp/Views/UserActions/AllBurgers.cshtml
@model IEnumerable<BurgerApp.Models.Burger>

@{
    ViewData["Title"] = "AllBurgers";
}


@if(@TempData["Buy_Alert"]!= null)
{
 <div class="alert alert-success" role="alert">
  @TempData["Buy_Alert"]
</div>   
}
@if(@TempData["AddToCart_Alert"] != null)
{
 <div class="alert alert-success" role="alert">
  @TempData["AddToCart_Alert"]
</div>   
}
@if(@TempData["RemoveCartItem_Alert"]!= null)
{
 <div class="alert alert-success" role="alert">
  @TempData["RemoveCartItem_Alert"]
</div>   
}
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            
            <div class="container-fluid">
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                   
                    <ul class="navbar-nav flex-grow-1">
                    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserActions" asp-action="ViewCart" ><h4>View Cart</h4></a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserActions" asp-action="ViewBill"><h4>View Bill</h4></a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>


<h1>Burgers Menu</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var item in Model)
            {
                <div class="col">
                    <div class="card">
                        <div class="card-body">

                            <h5 class="card-title">
                                <a>@Html.DisplayFor(modelItem => item.Burger_Name)</a>
                            </h5>
                            <!-- Text -->
                            <img class="card-img-top" src=@item.Img  alt="Card image cap" height="300px" width="300px">
                            <p class="card-text">
                                <h3 hidden>Id : @Html.DisplayFor(modelItem => item.Id)</h3>
                                <h3>Available at : @Html.DisplayFor(modelItem => item.Burger_Location)</h3>
                                <h3>Price : @Html.DisplayFor(modelItem => item.Price)</h3>
                                <h3>Quantity : @Html.DisplayFor(modelItem => item.Quantity)</h3>
                                <button type="button" class="btn btn-info"><a asp-action="AddToCart" asp-route-id="@item.Id">Add To Cart</a>
                                </button>
                                </p>
                        </div>
                    </div>
                </div>
                }
         <div>
    </div>
    </div>

Project/BurgerApp/Views/UserActions/Buy.cshtml
@model BurgerApp.Models.Buy

@{
    ViewData["Title"] = "Buy";
}

<h1 id="heading">Buy</h1>
@if(@TempData["Alert"]!= null)
{
 <div class="alert alert-success" role="alert">
  @TempData["Register_Alert"]
</div>   
}
<head>
<style>
body{
           
            background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
        }
          .row{
            justify-content:center;
            background-color:transparent;
            font-size:20px;


        }
        input{
            height:40px;

        }
        #heading{
             text-align:center;
        }
        #btn1,#btn2{
            margin-left :70px;
        }

</style>
</head>
<hr />
<button type="button" class="btn btn-info"><a asp-action="AllBurgers">Home</a>
                                </button>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Buy">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" min="1" required />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group" >

                <input type="submit" value="Submit" class="btn btn-info" id="btn1"/>
            <a  id="btn2" class="btn btn-info"  asp-action="ViewCart">Back</a>
            </div>
            <br />
            
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Project/BurgerApp/Views/UserActions/Confirm.cshtml
<head>
<style>
body{
     background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
     }
 </style>
 </head>
        <button type="button" class="btn btn-info"><a asp-action="AllBurgers">Home</a>
                                </button>
<h1>
    Thank you !
</h1>
<h2>
    Bill Paid !
</h2>

Project/BurgerApp/Views/UserActions/OrderHistory.cshtml
@model IEnumerable<BurgerApp.Models.History>

@{
    ViewData["Title"] = "OrderHistory";
}

<head>
<style>
body{
     background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
     }
 </style>
 </head>
        <button type="button" class="btn btn-info"><a asp-action="ViewBill">View Bill</a></button>
                                

<h1>Order History</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Burger_Id)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Burger_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Burger_Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Burger_Id)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Burger_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Burger_Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            
        </tr>
}
    </tbody>
</table>

Project/BurgerApp/Views/UserActions/RemoveFromBill.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Project/BurgerApp/Views/UserActions/ViewBill.cshtml
@model IEnumerable<BurgerApp.Models.Buy>

@{
    ViewData["Title"] = "ViewBill";
}
<head>
    <style>
        body{

            background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
        }
          .row{
            justify-content:center;
            background-color:transparent;
            font-size:20px;


        }
        #btn{
          margin-left:530px;
        }
        input{
            height:40px;

        }
        #heading{
             text-align:center;
        }
        .center {
  position: relative;
  padding: 50px 50px;
  background: #fff;
  border-radius: 10px;
}
.center h1 {
  font-size: 2em;
  border-left: 5px solid dodgerblue;
  padding: 10px;
  color: #000;
  letter-spacing: 5px;
  margin-bottom: 60px;
  font-weight: bold;
  padding-left: 10px;
}


.center .inputbox [type="button"] {
  width: 50%;
  background: dodgerblue;
  color: #fff;
  border: #fff;
}


    </style>
</head>




<div class="center">
    <button type="button" class="btn btn-info"><a asp-action="AllBurgers"><h4>Home</h4></a></button>
   <button type="button" class="btn btn-info"><a asp-action="OrderHistory"><h4>Order History</h4></a></button>

    <h2 id="heading">Bill</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Burger_Id)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Burger_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Burger_Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            float Total = 0;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Burger_Id)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Burger_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Burger_Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                @{
                    float price = item.Quantity * item.Price;
                }
                <td>
                    @Html.DisplayFor(modelItem => price)
                    @{

                        Total = price + Total;
                    }
                </td>
                <td>
                    <a asp-action="RemoveFromBill" asp-route-id="@item.Id" class="btn btn-info">Remove</a>
                </td>
            </tr>

<br />
        }

    </tbody>
   
</table>

  <h1>Checkout Now</h1>
  <form>
    <div class="inputbox">
         <label>Card Number</label><br />
      <input type="text" required="required">
     
    </div>
    <div class="inputbox">
        <label>Exp date</label><br />
      <input type="date" required="required">
      
    </div>
    <div class="inputbox">
        <label>Cvv Number</label><br />
      <input type="number" required="required">
      
    </div>
    <div class="inputbox">
        <label>Address</label><br />
      <input type="text" required="required">
      
    </div><br />
    <h2 id="heading">Total Price : @Total</h2>
    <br />
    <div class="inputbox">
      <input type="submit" value="Confirm" asp-action="Confirm" asp-controller="UserActions" class="btn btn-success">
    </div>
  </form>
</div>

Project/BurgerApp/Views/UserActions/ViewCart.cshtml
@model IEnumerable<BurgerApp.Models.Cart>

@{
    ViewData["Title"] = "ViewCart";
}
<head>
    <style>
        body{
           
            background: -webkit-linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%); background: linear-gradient(360deg,#e9fbcf 10%,#1d7d8e 360%);
        }
    </style>
</head>
<h1>ViewCart</h1>
<button type="button" class="btn btn-info"><a asp-action="AllBurgers">Home</a></button>

<table class="table">
    <thead>
        <tr>
            <th>Burger Img</th>
            <th>
                @Html.DisplayNameFor(model => model.Burger_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Burger_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Burger_Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="@item.Img" height="100px" width="100px"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Burger_Id)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Burger_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Burger_Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                 <button type="button" class="btn btn-info"><a asp-action="Buy" asp-route-id="@item.Id">Buy Now</a> </button>
                  <button type="button" class="btn btn-info"><a asp-action="RemoveCartItem" asp-route-id="@item.Id">Delete</a></button>
                
            </td>
        </tr>
}
    </tbody>

           
</table>